name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run unit tests
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Force XCode 12.5
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app

      - name: Generate xcodeproj
        run: swift package generate-xcodeproj

      - name: Run tests
        run: xcodebuild test -destination 'name=iPhone 11' -scheme 'SimpleButton-Package'
